PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://purl.org/phenoscape/vocab.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX owlet: <http://purl.org/phenoscape/owlet/syntax#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX StandardState: <http://purl.obolibrary.org/obo/CDAO_0000045>

SELECT ?match ?score ?query ?corpusprofile
WHERE
{
?match ps:combined_score ?score .
?match ps:for_query_profile ?query .
?match ps:for_corpus_profile  ?corpusprofile .


}