PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
CONSTRUCT { 
?s rdfs:subClassOf ?o .
}
FROM <http://kb.phenoscape.org/>
WHERE { 
    ?s rdfs:subClassOf* ?o .
    FILTER(isIRI(?s))
    FILTER(isIRI(?o))
}
